[tool.black]
line-length = 88

[flake8]
max-line-length = 88
#ignore = 'E1, E2, E3, E5, E722, E731, W503, W504'

[tool.isort]
line_length = 88
# make compatible with black
multi_line_output=3
include_trailing_comma='True'
force_grid_wrap=0
use_parentheses='True'
ensure_newline_before_comments='True'
known_third_party=''

